name: build for windows

on:
    push:
        branches: [main, master]
    workflow_dispatch:

jobs:
  main:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: dev
      - run: flutter build windows
